services:
    evolution-api:
        container_name: evolution_api
        image: atendai/evolution-api:v2.1.1
        restart: always
        ports:
            - "8080:8080"
        env_file:
            - .env
        volumes:
            - evolution_instances:/evolution/instances
    postgres:
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: evolution
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    redis:
        image: redis:7-alpine
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        restart: unless-stopped
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@gmail.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5000:80"
        depends_on:
            - postgres
        restart: unless-stopped

volumes:
    postgres_data:
    evolution_instances:
    redis-data:
